// ─── Agent identity: pure, testable ─────────────────────────────────────

export interface AgentIdentity {
  /** Session-stable random id, generated once per session. */
  id: string;
  /** User-set label via /agent-name command. */
  label?: string;
  /** Environment override (CMUX_AGENT_NAME). */
  env?: string;
}

/** Generate a short random id for agent identity. */
export function generateId(): string {
  return Math.random().toString(36).slice(2, 6);
}

/**
 * True when `name` looks like an id produced by {@link generateId} — a
 * four-character lowercase alphanumeric string. Used to skip rename
 * broadcasts when no one could have known the old name anyway.
 */
export function isAutoGeneratedName(name: string): boolean {
  return /^[a-z0-9]{4}$/.test(name);
}

/**
 * Resolve the display name from identity.
 * Priority: env > label > id.
 */
export function resolveIdentity(identity: AgentIdentity): string {
  if (identity.env) return identity.env;
  if (identity.label) return identity.label;
  return identity.id;
}

/** Create a new identity with a label set. Returns a new object. */
export function setLabel(
  identity: AgentIdentity,
  label: string,
): AgentIdentity {
  return { ...identity, label };
}

/** Serializable form for session persistence. */
export function identityToData(identity: AgentIdentity): {
  id: string;
  label?: string;
} {
  return { id: identity.id, label: identity.label };
}

/** Restore identity from persisted session data + current env. */
export function identityFromData(
  data: { id?: string; label?: string },
  env?: string,
): AgentIdentity {
  return {
    id: data.id || generateId(),
    label: data.label,
    env,
  };
}
